=== lukaszSieczkowski/EU_Countries_WebService/src/main/resources/xsd_files/response/xsd/CountryDetailsResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/CountryDetailsResponse"
	xmlns:tns="http://www.example.org/CountryDetailsResponse"
	elementFormDefault="qualified">

	<element name="countryDetailsReponse" type="tns:CountryDetailsResponse"></element>

	<complexType name="CountryDetailsResponse">
		<sequence>
			<element name="countryDetails" type="tns:CountryDetails"></element>
		</sequence>
	</complexType>

	<complexType name="CountryDetails">
		<sequence>
			<element name="area" type="string"></element>
			<element name="population" type="long"></element>
			<element name="capital" type="string"></element>
			<element name="currency" type="string"></element>
			<element name="gros_domestic_product" type="long"></element>
			<element name="gros_domestic_product_per_person" type="long"></element>
		</sequence>
	</complexType>
</schema>

=== lukaszSieczkowski/EU_Countries_WebService/src/main/resources/xsd_files/response/xml/CountryDetailsResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:countryDetailsReponse xmlns:tns="http://www.example.org/CountryDetailsResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/CountryDetailsResponse ../xsd/CountryDetailsResponse.xsd ">
  <tns:countryDetails>
    <tns:area>tns:area</tns:area>
    <tns:population>0</tns:population>
    <tns:capital>tns:capital</tns:capital>
    <tns:currency>tns:currency</tns:currency>
    <tns:gros_domestic_product>0</tns:gros_domestic_product>
    <tns:gros_domestic_product_per_person>0</tns:gros_domestic_product_per_person>
  </tns:countryDetails>
</tns:countryDetailsReponse>
