=== lukaszSieczkowski/EU_Countries_WebService/src/main/resources/xsd_files/model/xsd/GrosDomesticProduct.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/GrosDomesticProduct"
 xmlns:tns="http://www.example.org/GrosDomesticProduct" elementFormDefault="qualified">
 
 <element name="grosDomesticProduct" type="tns:GrosDomesticProduct"></element>
 
 <complexType name="GrosDomesticProduct">
 <sequence>
 	<element name="gdp_2003" type="double"></element>
 	<element name="gdp_2004" type="double"></element>
 	<element name="gdp_2005" type="double"></element>
 	<element name="gdp_2006" type="double"></element>
 	<element name="gdp_2007" type="double"></element>
 	<element name="gdp_2008" type="double"></element>
 	<element name="gdp_2009" type="double"></element>
 	<element name="gdp_2010" type="double"></element>
 	<element name="gdp_2011" type="double"></element>
 	<element name="gdp_2012" type="double"></element>
 	<element name="gdp_2013" type="double"></element>
 	<element name="gdp_2014" type="double"></element>
 </sequence>
 </complexType>
</schema>

=== lukaszSieczkowski/EU_Countries_WebService/src/main/resources/xsd_files/model/xml/GrosDomesticProduct.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:grosDomesticProduct xmlns:tns="http://www.example.org/GrosDomesticProduct"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/GrosDomesticProduct ../xsd/GrosDomesticProduct.xsd ">
	
	<tns:gdp_2003>0.0</tns:gdp_2003>
	<tns:gdp_2004>0.0</tns:gdp_2004>
	<tns:gdp_2005>0.0</tns:gdp_2005>
	<tns:gdp_2006>0.0</tns:gdp_2006>
	<tns:gdp_2007>0.0</tns:gdp_2007>
	<tns:gdp_2008>0.0</tns:gdp_2008>
	<tns:gdp_2009>0.0</tns:gdp_2009>
	<tns:gdp_2010>0.0</tns:gdp_2010>
	<tns:gdp_2011>0.0</tns:gdp_2011>
	<tns:gdp_2012>0.0</tns:gdp_2012>
	<tns:gdp_2013>0.0</tns:gdp_2013>
	<tns:gdp_2014>0.0</tns:gdp_2014>
	
</tns:grosDomesticProduct>
