=== lukaszSieczkowski/EU_Countries_WebService/src/main/resources/xsd_files/model/xsd/Unemployment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.countries.com/Unemployment"
	xmlns:tns="http://www.countries.com/Unemployment" elementFormDefault="qualified">
	
	<element name="unemployment" type="tns:Unemployment"></element>
	
	<complexType name="Unemployment">
		<sequence>
			<element name="unemployment_2003" type = "double"></element>
			<element name="unemployment_2004" type = "double"></element>
			<element name="unemployment_2005" type = "double"></element>
			<element name="unemployment_2006" type = "double"></element>
			<element name="unemployment_2007" type = "double"></element>
			<element name="unemployment_2008" type = "double"></element>
			<element name="unemployment_2009" type = "double"></element>
			<element name="unemployment_2010" type = "double"></element>
			<element name="unemployment_2011" type = "double"></element>
			<element name="unemployment_2012" type = "double"></element>
		</sequence>
	</complexType>
</schema>

=== lukaszSieczkowski/EU_Countries_WebService/src/main/resources/xsd_files/model/xml/Unemployment.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:unemployment xmlns:tns="http://www.countries.com/Unemployment"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.countries.com/Unemployment ../xsd/Unemployment.xsd ">
	
	<tns:unemployment_2003>0.0</tns:unemployment_2003>
	<tns:unemployment_2004>0.0</tns:unemployment_2004>
	<tns:unemployment_2005>0.0</tns:unemployment_2005>
	<tns:unemployment_2006>0.0</tns:unemployment_2006>
	<tns:unemployment_2007>0.0</tns:unemployment_2007>
	<tns:unemployment_2008>0.0</tns:unemployment_2008>
	<tns:unemployment_2009>0.0</tns:unemployment_2009>
	<tns:unemployment_2010>0.0</tns:unemployment_2010>
	<tns:unemployment_2011>0.0</tns:unemployment_2011>
	<tns:unemployment_2012>0.0</tns:unemployment_2012>
	
</tns:unemployment>
